# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'TB_Client_Seller' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TB_Client_Seller

 	pod 'Alamofire', '~> 3.0'

	pod 'SwiftQRCode'

	pod 'KeychainSwift', '~> 3.0'

	pod 'Bluetonium'

	pod 'BButton'

	pod 'ObjectMapper', '~> 1.3'

	pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'

	pod 'MBProgressHUD', '~> 0.9.2'

	pod 'SCLAlertView'

	pod 'AlamofireNetworkActivityIndicator', '~> 1.0'

  target 'TB_Client_SellerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TB_Client_SellerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
